### ISSUE TITLE
Definitions lack categories

### ISSUE THREAD

**Issue by CoolOppo** [ntkme/dictionary#1]
The definitions frequently come up without listing the categories/tags they belong to.

# Example

## Actual Google definition:

![](http://i.imgur.com/xC1wXmQ.png)

## This project's definition:

![](http://i.imgur.com/hTdf2ut.png)

**Comment by ntkme** [comment]
The API in this project is from Google Docs, and it doesn't have any categories or tags, which is slightly different from the result you see in Google Search. Google Search wrappers its API calls, so it's almost impossible to get the original API call.
